name: Deploy BigLedger Wiki to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.134.2/hugo_extended_0.134.2_linux-amd64.tar.gz
          tar -xzf hugo_extended_0.134.2_linux-amd64.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version

      - name: Build Hugo site
        run: hugo --minify

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          # Deploy without CloudFront invalidation first
          hugo deploy --target=production --maxDeletes -1
          
      - name: Invalidate CloudFront
        if: success()
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3FOFD9ZXC2QVT \
            --paths "/*" \
            --query 'Invalidation.Id' \
            --output text

      - name: Verify deployment
        run: |
          echo "Site deployed to: https://wiki.bigledger.com"
          echo "Checking if site is accessible..."
          curl -I https://wiki.bigledger.com || true